services:
  - type: web
    name: blog-it-by-rakib-mondal
    runtime: ruby
    repo: https://github.com/rakibM-04/blog-it
    branch: main
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-it-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    buildCommand: ./bin/build_script
    startCommand: bundle exec puma -C config/puma.rb

databases:
  - name: blog-it-db
    databaseName: blog_it_prod_db
    user: admin
    plan: free
    postgresMajorVersion: "13"

version: "1"
